### ISSUE TITLE
page "bloody stuff !" avec touts les paquets/lib qu'on recommande

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#223]
je met bloody car je pense à tous les bloody-* de @bloodyowl mais on peut imaginer faire des sections par langages et par exemple dans la section php on met symfony 2... :trollface: 
Enfin voyez le truc. Ouais / non ?

**Comment by MoOx** [comment]
osef. Cela dit faudra une page dans le style.

**Comment by kud** [comment]
Je trouve l'idée pas mal tout de même mais peut-être pas urgent oui.
