### ISSUE TITLE
Optimiser les images (poids + plusieurs tailles)

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.fr#305]

**Comment by MoOx** [comment]
Bon moi je pense qu'on doit faire ca en amont pour pas alourdir le repo. Si on garde des putains d'images de 2Mo, le repo va vite faire 100/200/500Mo et ça va pas être sympa à dl.

A la limite qu'on fasse des thumbs aux build pourquoi pas, mais selon moi il faut impérativement versionner des versions déjà optimisers sans quoi, ça va souler et le build prendra de plus en plus de temps, travis devant dl le repo à chaque fois.

**Comment by Macxim** [comment]
Tout à fait d'accord.

**Comment by kud** [comment]
Ouais désolé pour mon post, j'étais sous vindoz et j'ai zappé la partie opti. Faudrait proposer des outils en ligne dans le contributing.md (j'ai déjà tout le matos sous macosx pour ça) ou un tuto pour du cli node.

**Comment by MoOx** [comment]
Ok. Je ferme donc et on vera pour les thumbs si on en resent le besoin.
