### ISSUE TITLE
React ROADMAP

### ISSUE THREAD

**Issue by bloodyowl** [putaindecode/putaindecode.fr#315]
ref #251 

just so that everyone knows :

## breaking changes

- we'll drop `index.jade` files and put metadata at the top of markdown files directly 

```md
---
Title : Structurer son projet avec Revel et Mgo
Comments : true
Authors :
  - OwlyCode
Tags :
  - golang
  - mongo
  - revel
  - mgo
Date : 2013-11-11
---
```

- we'll stop using gulp, `npm scripts` will manage everything with bin directly
- we move from browserify to webpack (enabling the use of react-hot-loader, and makes us write less config)
- move from SuitCSS to cssrecipes
- stop using jade & use react for the whole site
- stop pre-generating pages in dev mode, and only prerender pages with travis-ci

**Comment by Nyalab** [comment]
Je peux avoir un ~topo~ (quelques mots, vous faites pas chier) sur quoi je pourrais commencer à bosser ?

**Comment by lionelB** [comment]
Coucou,
 je pensais justement à m' y mettre aussi maintenant que j'ai fait mon site. Les trucs easy, c'est de commencer avec les petits composants sur les pages ensuite un compo par type de page.

**Comment by bloodyowl** [comment]
just for the record, I worked a bit on the server/client cohabitation and came up with this API : https://gist.github.com/bloodyowl/384dc4706896d1a6811b

I got the code working, just need to add some tests.

the chosen stack is :
- ES6 (with some nice ES7 experimental features e.g. https://gist.github.com/bloodyowl/384dc4706896d1a6811b#file-poststore-js-L8-L16)
- webpack
- dispatcher-agnostic actions
- stores & dispatchers which both are singletons on the client, but simple instances created at runtime on the server (for obvious concurrency reasons)

I'll send the PR very soon.

**Comment by kud** [comment]
It could be great to make an article about the migration. In order to be useful for our readers.

**Comment by bloodyowl** [comment]
we'll update the "how to contribute" page for that. 

about the migration I think I'll write about the constraints of sharing a flux architecture between client and server and how this solution works them out.

**Comment by kud** [comment]
By the way, what's the point of this migration? Do we will get a more optimised system? Will it be easier for the contributor?

**Comment by bloodyowl** [comment]
- better performance as this is a pre-rendered SPA (minimal set of requests are made when you navigate through the site)
- better testability (everything used to generate the pages is plain JavaScript)
- lighter codebase (no more gulp hacks)
- proper routing system
- much faster page generation
- no more issues with async page generation
- easier to contribute (one file for an article, one file for an author)

**Comment by kud** [comment]
It's really the last point I'd love to see. Making a post in the current system is quite boring.

**Comment by lionelB** [comment]
Yop, 
I'm all ok with the chosen stack, I've just a some mixed feeling about Flux.
From my recent experience, I'm not sure Flux is mandatory for our kind of site (static site with few dynamic part, like the post page) and could add an overall complexity ( bootstrapping the right store depending on the current url same for the client).

I'm not against flux, just want to open the discussion 
 
Also, I would be glad to contribute to it ;-)

**Comment by MoOx** [comment]
Can't wait for this stack !

![vdamesplit](https://cloud.githubusercontent.com/assets/157534/6320038/2541c284-bad4-11e4-853d-7084f7ddb586.gif)

**Comment by kud** [comment]
metalsmith + cssnext could be enough but if you think this stack is great, so go ahead. I just want no compilation error the next time I write an article.

**Comment by MoOx** [comment]
Something like metalsmith can't work when you get more & more posts.

> I just want no compilation error the next time I write an article.

You do have some right now ?

**Comment by kud** [comment]
1/ Define why metalsmith can't make the deal
2/ No but I remember well irc bot project migration

**Comment by MoOx** [comment]
1/ metalsmith does not offer fast rebuild during dev, does not have a routing system and, ice on the cake, does not alllow to receive trolls about the stack ^^

2/ all the problems we got with that came from the multi channel thing. Anyway we do not put enough energy for this migration... It's just a useless irc bot, not a website with 10000 sessions per month and "serious" content.

**Comment by madx** [comment]
What about accessibility? Will the site still be browseable without JS?

**Comment by lionelB** [comment]
@madx tell me http://lumographe.fr

**Comment by madx** [comment]
Hmmm, looks neat :D

**Comment by MoOx** [comment]
Closing in favor of #352
