### ISSUE TITLE
async build issue related to jade-exports

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#328]
@bloodyowl j'ai pris un peu de temps pour regarder ce bug

![screen shot 2014-12-17 at 16 32 22](https://cloud.githubusercontent.com/assets/157534/5473536/6cd42514-860a-11e4-8a7a-0538816991e5.png)

url et MD ok, par contre contenu export (meta) pas ok (correspond à un autre post). J'ai fais du debug niveau jade-exports (output d'un json du cache) ça à l'air ok en fin de process.
J'ai fais un debug (console.log) dans le .jade les exports correspondent pas (pour ce post, en ce moment).

Ce bug est random dans le temps, mais lié au contenu/fichiers (en l'état je l'ai systématique en local).
Si on change/alourdi/ajoute un fichier ca peut changer de post affecté ou de meta (tout à l'heure j'ai eu les meta du post sublime text sur cette meme url - en local).

Si t'as une idée pour quick fix vite fait @bloodyowl je prends...

**Comment by madx** [comment]
FAUT FIXER ÇA MA GUEULE

**Comment by kud** [comment]
Dans l'idée, je trouve ça pas mal.

**Comment by MoOx** [comment]
c'est juste la loose.

**Comment by kud** [comment]
Tout ça parce que c'est moi et pas vous indiquer sur le post. Tssssssssssss.

**Comment by MoOx** [comment]
J'en peux plus de ce bug.

@bloodyowl t'en es où bichon avec la branche react ? T'as besoin d'aide ?

**Comment by MoOx** [comment]
bon faudrait pousser la branche react en l’état @bloodyowl.
Qu'on avance dessus. Je sais que ça te tient à coeur mais là en l'état le site est plus possible. Y'a des putains de bug de partout, j'avais quasi 1/3 des posts qui avaient le meme header...
Je viens de faire un deploy de p! à la main, c’est juste l'horreur.
Bon si on attendra mais on publie plus rien tant qu'on a pas réglé ça OU sortie la nouvelle version.

Je préfèrerais une version react qui marche sans server side quelques jours, que ce qu'on a aujourd'hui...

@bloodyowl à la limite fait une PR, et si tu veux vraiment tout vérifier par toi même, on fera des PR sur ta PR pour que tu puisses controler ?

**Comment by MoOx** [comment]
Bon je ferme cette issue car elle me file la nausée d'ailleurs.

**Comment by madx** [comment]
Pour info, j'avais aucun problème au build

J'ai mis à jour mes node_modules, et hop, j'ai eu des problèmes. Voici la liste des anciens et nouveaux modules au cas où ça puisse aider

https://gist.github.com/madx/9777681462b1af337e6d

**Comment by MoOx** [comment]
Pas tant de diff que ca en fait. npm shrinkwrap pourrait patcher l'histoire.

**Comment by MoOx** [comment]
I didn't succeed to get a correct build even with old packages. This bug is old so not sure @madx if you didn't miss something else. Anyway, #361 !
