### ISSUE TITLE
Article sur HATEOAS

### ISSUE THREAD

**Issue by awillemant** [putaindecode/putaindecode.fr#330]
Bonjour à tous,

Bravo pour ce blog, j'adore l'esprit décalé ;)

Un article sur les API ReST et l'Hypermedia est-il pertinent pour Putain de code ?

Je compte parler des niveaux de maturité de Richardson, de l'Hypermedia As The Engine Of Application State et d'un exemple d'implémentation.

Je reste à votre dispo pour toute information complémentaire.

Merci d'avance !

**Comment by awillemant** [comment]
PR poussée

**Comment by MoOx** [comment]
PR mergé
