### ISSUE TITLE
proposition de post: après 3 jours avec Vim

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#331]
titre: "Il démarre Vim par erreur, ce qui se passe ensuite est tout simplement bluffant"
ou un titre dans le genre.

**Comment by bloodyowl** [comment]
:+1:

je peux aussi participer à l'écriture si ça te branche

**Comment by MoOx** [comment]
Je pousserais rapidement un plan pdt que c'est chaud, on itèrera dessus.

**Comment by Nyalab** [comment]
Je ne souhaite pas participer à l'écriture mais je pourrais peut être vous donner des retours sur mon xp à moi pour affiner, si j'ai pas eu les mêmes réactions ou compréhensions ;-)

**Comment by magsout** [comment]
:+1:
