### ISSUE TITLE
Proposition de post : Shake ton DOM - GreenSock Animation Platform tut'

### ISSUE THREAD

**Issue by justinmarsan** [putaindecode/putaindecode.fr#333]
https://greensock.com/gsap

Librarie pour faire des animations, changer les propriétés css toussa, en allant un peu au-delà du $(this).animate() de jQuery...

**Comment by MoOx** [comment]
Pourquoi pas.
Tu vas reprendre ça j'imagine https://greensock.com/get-started-js ?

**Comment by justinmarsan** [comment]
Le contenu sera similaire (forcément) mais un peu condensé parce que c'est hyper long, et j'ajouterai une partie sur DrawSVG qu'ils ont pas "tutorialée" encore qui est dans la dernière version de la lib ( http://greensock.com/drawSVG )

**Comment by magsout** [comment]
Interessant, des nouvelles ?

**Comment by justinmarsan** [comment]
J'ai pas eu de retours, pas le sentiment que @MoOx soit hyper emballé, pas d'autres retours du coup j'ai pas trop bougé pour le moment.

ScrollMagic (une lib d'animation au scroll qui utilise GSAP) vient de sortir en v2, je suis en contact avec le dev de la lib, je vais m'occuper du wiki et du tutoriel *officiel* et ensuite faire un tut qui va avec en anglais spécifique à GSAP, j'avais pour projet de proposer la traduction de cet article en anglais après...

Mais si y'a des retours ou que vous pensez que ça peut être cool de le faire, je suis toujours motivé.

**Comment by bloodyowl** [comment]
quitte à faire un article sur les animations, je préférerais qu'on aille vraiment dans le détail de comment le faire soi-même.

```javascript
const duration = 300
const tick = () => {}

function animate({duration, tick} = {duration, tick}) {
  return new Promise((resolve) => {
    const start = Date.now()
    const onTick = () => {
      const now = Date.now()
      const progress = (now - start) / duration
      if(progress >= 1) {
        tick(1)
        resolve()
        return
      }
      tick(progress)
      requestAnimationFrame(onTick)
    }
    requestAnimationFrame(onTick)
  })
}
```

&

```javascript
animate({
  duration : 500,
  tick(progress) {
    console.log(progress)
  }
})
  .then(() => console.log("done"))
```

parce qu'honnêtement je vois pas la valeur ajoutée de gsap

**Comment by lionelB** [comment]
@bloodyowl je connais pas très bien (je l'avais à pein utiliser en flash alors ça date) mais il me semble que gsap offre pas mal de truc intéressant comme la timeline, la possibilité de play / pause / reverse, une syntaxe de chaining qui fonctionne pas mal pour du tweenn le support du easing. 
Pour animer un scale de bouton c'est pas vraiment utile. par contre pour ce genre de truc http://www.shanemielke.com/archives/usopen-sessions/ ça a déjà plus de sens

**Comment by bloodyowl** [comment]
wai c'est du sugar quoi

**Comment by lionelB** [comment]
ouais comme n'importe quelle lib en fait ;-)

**Comment by justinmarsan** [comment]
Je suis d'accord que pour des animations relativement simples c'est pas ouf, par contre effectivement les  timelines sont assez pratiques pour écrire sont code, rien que les marqueurs nommés, qui permettent de se référer à un nom dans la timeline pour positionner le début d'un tween, etc etc...

Après je suis d'accord que c'est pas du from-scratch et qu'en soit la lib est pas fondamentale, mais si tu veux que le code qui gère tes animations et transitions soit lisible, faudrait ré-écrire une lib du même genre au final, sinon tu te retrouves avec 40 lignes pour passer d'un écran à un autre dans une web-app par exemple, c'est pas gérable.

Mais bon, c'pas pour rien qu'il y a les propositions de post, donc à débattre, mais je peux comprendre qu'on voit pas l'utilité, ça dépend aussi de ce qu'on en fait...

**Comment by bloodyowl** [comment]
wai ok mais pour le coup, pour un article sur p!, je pense que notre visée c'est plus de donner les clés pour comprendre que de donner les clés pour faire :smile:

**Comment by lionelB** [comment]
@bloodyowl je suis d'accord avec ça \o/

**Comment by MoOx** [comment]
du coup ?

**Comment by MoOx** [comment]
yakékun

**Comment by kud** [comment]
Y'a sonneper !

**Comment by Nyalab** [comment]
daed

**Comment by magsout** [comment]
Pas de réponse, bein pas de réponse.
