### ISSUE TITLE
Retur d'expérience sur la mise en place react server side react router et flux

### ISSUE THREAD

**Issue by lionelB** [putaindecode/putaindecode.fr#336]
Suite à mes expérimentations (https://github.com/lionelB/lumographe.fr) , je pensais faire un post de récap. Le titre reste à trouver
le plan prévu :

## intro
motivations et intérêts.
Présentation des briques (react-router, flux)

## Principe et mise en place
Intégration avec express  (middleware)
1- serveur
2- initialisation du client (synchro des stores)
3- Navigation

## conlusion
Difficultés rencontrés. peut être aussi un test webperf avant/après si c'est pas trop relou

##links

Des idées de ce que vous aimeriez avoir comme infos supplémentaires ?

**Comment by MoOx** [comment]
Bah ca serait top qu'on ai même ca sur le site de p! :)
Mais sinon go.
J'ai un peu peur que le post soit long mais à voir.

**Comment by Nyalab** [comment]
:+1:

**Comment by magsout** [comment]
:camel:  (y a pas d'âne)

**Comment by lionelB** [comment]
@MoOx  en fait, je pense que je vais découper:
la première partie porte sur react-router en fait (avec un peu de flux à la fin) plus les problématiques que j'ai rencontrés.

y'aura surement un post " Mes p! de problèmes " ou je parlerais des pb que j'ai eu 
- l'intégration de react-hotloader avec un serveur existant qui m'a causer quelques soucis 
- la gestion des 404
- l'initialisation des stores coté serveur et coté client

J'avoue que j'ai un peu de mal à mettre en forme cela de manière cohérente, donc je vous solliciterai pour la relecture.

et sinon pour la versions react de P!,  je voulais finir le post avant de m'y atteler mais c'est prévu.

**Comment by lionelB** [comment]
incoming!! putaindecode/putaindecode.fr/pull/337 
et merci @Macxim pour les typo, c'est mergé

**Comment by lionelB** [comment]
Done! Thx all, pour info le build est  niquel
 J'ai fais depuis le téléphone, c'est rigolo

**Comment by MoOx** [comment]
Héhé :)
GG.

**Comment by Nyalab** [comment]
bravo mec

**Comment by lionelB** [comment]
je  peux  vous laisser faire le tweet demain matin ? j'ai pas les accès

**Comment by MoOx** [comment]
ouais t'inkiète pas. Tu les as si tu cherches dans les docs google partagés. Si y'a pas demande ;)
