### ISSUE TITLE
Comment debugguer facilement du web même sur tablettes et téléphones

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.fr#350]
Un 'tit aperçu de l'article que je compte publier : http://simp.ly/publish/LWqQqx

Si vous êtes ok dans l'ensemble, je PR et on corrige ça plus en détail.

**Comment by magsout** [comment]
:+1: 

je ne connaissais pas weinre, bon après j'ai jamais eu à debug du Android browser de merde.

Par contre pour la partie Chrome, pour debugger du chrome faut forcément passer par about:inspect ? non ? peut-être le mentionner ?

**Comment by kud** [comment]
J'avoue, je vais le rajouter en effet.

**Comment by lionelB** [comment]
J'ai lu rapidement hier. Je te fais un retour un peu pêle-mêle  

Globalement, je pense que ca pourrait etre pas mal de découper en plusieurs post
(debug weinre,  FF webide,  debug http), après lecture du post, j'ai trouvé me tout un peu décousu.

je trouve que les screen shot des différent browser n'apporte pas grand chose.

Sur la partie quid du mobile, l'explication me semble un peu magique (connecter votre appareil, lancer Chrome sur desktop et voila la connexion... )  moi la dernière fois que j'ai essayé, il fallait lancer adb, configurer la tablette en mode Multimédia,  se connecter à  une url depuis le browser desktop, bref un truc un peu plus compliqué. On dirait que ça c'est vachement amélioré. Est ce que ca serait pas plus cohérent de mettre la partie FF webide a ce moment là ?

J'aurais plus orienté la suite autour de weinre qui permet d'avoir des outils adéquats pour débugger  Android Browser ce qui rend le passage cli android presque inutile. on voit dans le screenshot  pleins d'info de debug mais pas vraiment utile pour du debug web (je sais pas si je suis très clair)

Concernant weinre, ça pourrait être bien d'expliquer un peu plus le principe de weinre (ça lance un serveur de debug, un script à ajouter, l'intéret par rapport à firebug lite) avant de rentrer dans l'install à proprement parlé.

sinon y'a pleins d'infos mais ça gagnerait en clarté si on découpé je pense.
Merci pour toute ces infos en tout cas.

**Comment by kud** [comment]
+1 pour les screenshots, je pense pas que ce soit utile de tout détailler sur ça.

Okay pour parler un peu plus de weinre.

Par contre, en effet, ils ont grandement amélioré le debug sous adb / chrome / firefox ide. Plus besoin de lancer ça par cli.

**Comment by magsout** [comment]
Même sur firefox, entre les premières version du `se connecter à distance et webide, tout est nativement geré et installé. Juste à confirmer la connexion sur la tablette

**Comment by kud** [comment]
rien compris à ce que tu as dit @magsout

**Comment by MoOx** [comment]
Je rejoins totalement les points de @lionelB.
Ça mérite a être découpé et mieux ficelé.

**Comment by magsout** [comment]
@kud 
>rien compris à ce que tu as dit @magsout

Que maintenant, debugger Chrome mobile ou Firefox mobile avec les dev-tools des versions desktop est nettement plus facilement et accessible car il n'y a plus rien à installer contrairement à avant ou il fallait installer adb, installer l'addon truc etc... C'était juste pour rebondir sur les propos de @lionelB

**Comment by kud** [comment]
Oui je suis d'accord.

**Comment by kud** [comment]
Mieux là ? https://app.simplenote.com/publish/LWqQqx

Plus d'explication sur WebIDE ?

**Comment by kud** [comment]
poke @putaindecode/authors

**Comment by magsout** [comment]
Un Bon article. 

Quelques tournures à revoir et quelques fautes mais ça se corrigera en PR. 👍

**Comment by kud** [comment]
Voulez-vous plus d'explications sur WebIDE et Weinre ou c'est ok pour vous ?

**Comment by lionelB** [comment]
c'est bon si je relis ça ce soir et je te dit ?

2015-03-19 17:59 GMT+01:00 Erwänn Mest <notifications@github.com>:

**Comment by kud** [comment]
Pas de souci, ;)

**Comment by MoOx** [comment]
J'aurais fait ce post en 2 temps:
- une présentation plus en détails de webide (pas forcément en expliquant tout, ce que fait déjà mdn) (+ cliffanger de fin: ca marche pas avec android browser)
- un post sur weinre

Tout ça dans une categorie /posts/browsers/debug/ (ou un truc du genre) ou on y mettra un petit index qui fait un très court résumé en quelques phrases des ces 2 posts (cf #344)

Note: le lien vers webide existe en fr https://developer.mozilla.org/fr/docs/Outils/WebIDE, on voit par contre que la trad est incomplète, ça peut être l'occassion de finir cette traduction :)

**Comment by magsout** [comment]
J'avais d'ailleurs fait un article sur les dev tools dans les navigateurs pour le rwd  http://www.splitfire.fr/blog/article/le-responsive-dans-nos-navigateurs

**Comment by lionelB** [comment]
Cool, c'est vraiment mieux pour ma part. 
sinon je pense que la capture d'écran de weinre apporte pas grand chose (beaucoup de texte).
En fait je me demande si développer la partie install de weinre pourrait pas sauter (ça resterai cohérent avec la partie webide) 

L'idée de @MoOx est pas mal si t'as envie de développer un peu plus les parties install/utilisation de weinre

ps : la partie sur les requête http me fait toujours l'effet du cheveux sur la soupe mais est utile donc je sais pas trop quoi dire 

en tout cas c'est beaucoup mieux, cohérent :+1:

**Comment by kud** [comment]
Okay, je vois.

Je pense que je vais améliorer la partie WebIDE et Weinre et je ferai une
PR.

2015-03-20 9:07 GMT+01:00 Lionel <notifications@github.com>:

> Cool, c'est vraiment mieux pour ma part.
> sinon je pense que la capture d'écran de weinre apporte pas grand chose
> (beaucoup de texte).
> En fait je me demande si développer la partie install de weinre pourrait
> pas sauter (ça resterai cohérent avec la partie webide)
>
> L'idée de @MoOx <https://github.com/MoOx> est pas mal si t'as envie de
> développer un peu plus les parties install/utilisation de weinre
>
> ps : la partie sur les requête http me fait toujours l'effet du cheveux
> sur la soupe mais est utile donc je sais pas trop quoi dire
>
> en tout cas c'est beaucoup mieux, cohérent [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/putaindecode/putaindecode.fr/issues/350#issuecomment-83946102>
> .
>



-- 
*Erwann Mest*
kud.io

**Comment by Nyalab** [comment]
Rien à redire pour moi, le fond est bon et à ne pas découper, si on est dans l'optique debug, on sait de quoi tu veux parler dans l'article, du coup, pas besoin de découper ou expliquer pendant 3 phrases ce que tu dis concrètement en une. À part la forme, qui est un peu chelou, mais ça rendra différemment sur p! je pense.

Du coup, pas beosin de retouche pour moi, je vois pas le besoin de découper et on passe concrètement à ce qu'on veut d'une partie à l'autre (console, network, dom, ...). :shipit:

**Comment by kud** [comment]
Je ne souhaite pas découper, je pense que l'article se base sur comment débugguer, et la personne regarde ce qui l'intéresse.

Par contre, je trouve la partie WebIDE et Weinre un peu trop légère. Je vais la détailler.

Merci pour vos retours.

**Comment by kud** [comment]
Je pense cette fois-ci avoir fini ce post : http://simp.ly/publish/LWqQqx

Dites-moi ce que vous en pensez et avec un peu de chance, on peut déployer ça la semaine prochaine.

Par contre, je suis assez embêté par notre système de blog au vu des propos https://github.com/putaindecode/putaindecode.fr/issues/352

Que puis-je faire ? est-il possible tout de même de publier ?

**Comment by MoOx** [comment]
Quelques petits points à revoir dans la forme mais ça attendra une PR.

Tu peux publier si et seulement si tu règles la #328 ce qui pourrait se faire "facilement" finalement vu les propos de @madx .

**Comment by magsout** [comment]
:shipit:
