### ISSUE TITLE
Ajax, localStorage et pushState pour un site plus rapide

### ISSUE THREAD

**Issue by justinmarsan** [putaindecode/putaindecode.fr#358]
J'ai commencé à bosser sur un petit projet, je me dis que ça peut éventuellement être intéressant pour P!

L'idée de base étant de pre-loader les pages d'un "petit" site, de stocker le contenu dans localStorage et remplacer tout le body au clic sur un lien interne, pour éviter de perdre du temps sur l'établissement de la connection, le rechargement de certains éléments & co, avec pushState pour conserver le Back Button et l'historique.

J'ai déjà un plan grossier, c'est pas hyper complexe mais la technique me semble que très peu utilisés alors que ça serait applicable sur quasiment n'importe quel portfolio ou petit site (parce que y'a pas que les web apps dans la vie :D) et ça donne une occasion de jouer avec des techniques plutôt basique pour autre chose que mettre à jour un fil de news ou faire un Todo.

**Comment by justinmarsan** [comment]
* Comprendre ce qui freine entre un clic et l'affichage de la page suivante
* Pré-charger les pages internes pour supprimer toute latence et temps de téléchargement
* Garder le contenu des pages en mémoire avec localStorage
* Conserver l'historique et le Back Button avec pushState
* Limites et contraintes (onload event, etc)
* Autres resources (liens vers méthode pjax, plugin instantclick, autre)

**Comment by drazik** [comment]
Un sujet qui m'intéresse ! J'espère que ton post verra le jour :)

**Comment by kud** [comment]
+1 pour ce post, très intéressant @justinmarsan. ;)

**Comment by MoOx** [comment]
En fait c'est pjax + preload/cache.
j'ai un module de pjax qu'on pourrait améliorer dans ce sens https://github.com/MoOx/pjax

**Comment by kud** [comment]
Oui sauf que là, c'est expliqué en article, donc bien.

**Comment by lionelB** [comment]
Super idée. Si tu peux faire un bench avant/après selon les navigateurs, je pense que ça pourrait être taupe!

**Comment by MoOx** [comment]
@kud je ne disais pas qu'il ne fallait pas en faire un article. Je voulais juste confirmation par @justinmarsan que c'était bien "juste" pjax + preload/cache (un bon pjax incluant la conservation de l'historique) - et que éventuellement il pourrait contribuer à mon projet plutôt que d'en faire un autre à part (vu qu'il y aura bcp de code similaires).

@lionelB Je pense pas qu'un bench soit nécessaire, ça me parait évident temps qu'on a là plupart des sites sur des serveurs http1.x qu'économiser des queries http est une bonne idée.

**Comment by justinmarsan** [comment]
Oulah, beaucoup de réponses !

@drazik @kud @lionelB ravi que ça vous plaise comme idée, pour une fois que je propose pas un truc trop de noobzor, ça change !

@MoOx j'ai fait le tour de ton repo, effectivement l'idée est la même, c'est du pjax sauf qu'au lieu d'attendre le clic, de charger à l'avance et conserver le tout dans le localStorage pour que ça soit encore plus instantané tout au long de la navigation.

Par contre je trouve que ton script va "trop" loin pour le scope de l'article que j'avais en tête. Y'a beaucoup de configurations possibles et tout, c'est évidemment plus intéressant dans un usage réel, mais forcément ça complique et ça s'adapte pas forcément à tous les cas de figure, à choisir je préfèrerai partir sur quelque chose de beaucoup plus simple (modifier l'ensemble du <body> par exemple) et proposer en fin d'article des pistes pour ceux qui souhaitent aller plus loin, customiser pour leurs besoins spécifiques, etc etc.

Mais c'est intéressant quoi qu'il arrive, je vais regarder le code plus en détail, je pourrais trouver des trucs utiles dedans et voir comment tu t'y est pris !

@lionelB Je vois pas trop comment je pourrais faire de bench pour ça, ça change rien sur la première page visitée (voir un peu plus lourd pour le script en question) et après tu as plus aucun chargement de page synchrone, tout devrait être instantané donc 100% de millisecondes en moins sur toutes les pages sauf la première.

**Comment by MoOx** [comment]
@justinmarsan, justement mon point aurait été d'ajouter la fonctionnalité de preload dans la lib. Ton post pourrait expliquer le concept, ton approche en l'algo avec un peu de technique (pas poser un snippet de code à copier coller). Après tu fais comme tu le sens. C'était aussi pour t'économiser des bugs.

De plus, je pense que modifier tout le body risque de provoquer beaucoup de bugs (si tu as d'autres lib/code qui repose sur des élements du DOM existant. Je ne conseillerais vraiment pas cette approche.
En plus tu devras au minimum changer body + title + éventuellements certaines meta.

Tu comptes faire ça en vanillajs (commonjs)? Ou via jQuery?

**Comment by magsout** [comment]
Des nouvelles ?

**Comment by MoOx** [comment]
du coup ?

**Comment by MoOx** [comment]
yakekun?

**Comment by bloodyowl** [comment]
@JUSTINMARSAN LAST CALL

**Comment by Nyalab** [comment]
![](http://i.ytimg.com/vi/HgllDrrUgy8/hqdefault.jpg)

**Comment by bloodyowl** [comment]
on close?

**Comment by Nyalab** [comment]
Vazy on bois tg
Le 18 juin 2015 21:03, "Matthias Le Brun" <notifications@github.com> a
écrit :

**Comment by MoOx** [comment]
Pas de nouvelles ? Pas de nouvelles :/
