### ISSUE TITLE
Command-line utilities avec Node.js

### ISSUE THREAD

**Issue by magsout** [putaindecode/putaindecode.fr#359]
J'ai commencé à écrire un article sur comment faire un utililaire en ligne de commande avec Node. 

Comme expliqué dans l'article j'en ai écrit un, et j'ai voulu partager mon retour d'xp.

Pour le moment, juste une grosse intro. 

Je voulais tourner ça comme une espece de tuto, avec un exemple bateau et présenter quelques utilitaire sympa comme `commander` ou même `chalk`

https://gist.github.com/magsout/c7d49ab3336eaa7746f4

Comme d'hab, avant d'aller trop loin. Votre point vue, si c'est de la merde, ou si c'est cool.

poke @putaindecode/owners

**Comment by kud** [comment]
Un peu court mais intéressant.

**Comment by magsout** [comment]
Merci. C'est juste le début. Il manque toute la partie sur les exemples d'utilitaires mise en situations.

**Comment by MoOx** [comment]
Moi je trouve ça bien. Pas vraiment trop court. Les gens aiment les posts court (moi le premier). Ca peut être l'objet d'une serie comme j'ai en draft sur la CI.

**Comment by MoOx** [comment]
Closing in favor of #389
