### ISSUE TITLE
Considerer un metalsmith en attendant #361

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#363]
Tout est dans le titre.

Car on est plusieurs à avoir des posts dans le pipe.

Et que la #361 demande du temps. Plus qu'un metalsmith.

**Comment by lionelB** [comment]
t'as une idée du travail de migration des post ? 
je suppose qu'en attendant on pourrait ré-utilisé la css compilée et juste se concentrer sur la partie génération de post ?

**Comment by magsout** [comment]
Ouais alors l'idée est pas bête mais j'ai peur quand faisant ça on repousse ad vitam la version ReactJS...

**Comment by MoOx** [comment]
Les posts sont déjà migré sur la branche react, donc travail de migration rien à faire.

**Comment by kud** [comment]
+1 pour ça

**Comment by lionelB** [comment]
Il y a aussi la partie qui se branche sur l'api GH, pour choper les nouveaux post. la comme ca ca me parait t

**Comment by MoOx** [comment]
> pour choper les nouveaux post.

wat ?

**Comment by Nyalab** [comment]
c'est honteux d'en arriver là, franchement

**Comment by kud** [comment]
![](http://media.giphy.com/media/yO24rwRksHuqk/giphy.gif) @Nyalab

**Comment by MoOx** [comment]
Voilà le délire va être dans ce sens

- scripts sans runner (npm script)
- https://github.com/christophercliff/metalsmith-webpack
- https://github.com/yeojz/metalsmith-react-templates

On va surement faire ou refaire des plugins metalsmith mais vu la longueur du code, ca sera rapide comparé à un version full react.

**Comment by kud** [comment]
![](http://media.giphy.com/media/iqOeJ02g6yVdC/giphy.gif)

**Comment by lionelB** [comment]
> choper les nouveaux post.

Je voulais parler de choper les infos des auteurs, pardon.

**Comment by MoOx** [comment]
c déjà un script maison. aucun probleme.
