### ISSUE TITLE
implementing flux

### ISSUE THREAD

**Issue by bloodyowl** [putaindecode/putaindecode.fr#365]
en gros:

https://twitter.com/bloodyowl/status/588431263880650752
https://twitter.com/bloodyowl/status/588432109888483328
https://twitter.com/bloodyowl/status/588432173386100738

expliquer au fur et à mesure les volontés, leurs soucis d'implémentation & leurs solutions.

vu que les exemples seront en ES6, ça pourrait être cool juste après que @Nyalab ait commencé sa série de posts sur le sujet. vous en pensez quoi?

**Comment by magsout** [comment]
Mais carrément.

**Comment by MoOx** [comment]
Trop.

**Comment by lionelB** [comment]
j'en pense du bien !
