### ISSUE TITLE
merger CONTRIBUTING.md & le post comment-contribuer ?

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#370]

**Comment by madx** [comment]
Ouais, faudrait pas avoir 3 trucs à maintenir, surtout que la façon de contribuer se peaufine un peu tout le temps :D

**Comment by MoOx** [comment]
Faudrait comment contribuer en index avec les pages suivantes

- contenu
  - proposer un post
  - ecrire un post

- contribuer au site
  - fixer un bug
  - apporter une amélioration au site

Vous en pensez quoi ?

**Comment by Nyalab** [comment]
Je ne pense pas que ce soit une bonne idée de merger. Refaire au propre, pourquoi pas.

**Comment by MoOx** [comment]
Ouais du coup mon dernier point c'est plus "éclaté" que merger. Mais éviter toute redondance.

**Comment by lionelB** [comment]
:+1: pour les docs ciblée

**Comment by MoOx** [comment]
On va update comment contribuer pourqu'il décharge une partie sur le CONTRIBUTING.md
