### ISSUE TITLE
Proposition de post: découverte de webpack

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#373]
Je vais mettre un petit webpack en place pour le projet pour build css/js donc je propose un petit post rapide dessus.

Je compte faire ca en es6 (coucou @Nyalab)

**Comment by lionelB** [comment]
:+1:

**Comment by bloodyowl** [comment]
:+1:

**Comment by magsout** [comment]
:+1:

**Comment by MoOx** [comment]
Bon je pense tenter d'accélérer un peu la sortie des posts et à passer à mardi/jeudi car j'en ai un paquet dans le pipe. Du coup je passerais le premier de la CI demain et mardi celui sur webpack (que j'aurais mis en PR avant). Ca vous dit ?

**Comment by magsout** [comment]
OH oui, apparement beaucoup de monde attend ton post ;)

**Comment by magsout** [comment]
:+1:
