### ISSUE TITLE
Inliner les icons svg afin de pouvoir récupérer les couleurs :)

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#374]

**Comment by bloodyowl** [comment]
faut foutre un webpack avant pour les inliner proprement IMO

**Comment by magsout** [comment]
@MoOx 
>Puis là de toute façon je pense que je vais le faire sans webpack.

Et tu veux fais comment ?

**Comment by MoOx** [comment]
fs.readFile ? (on est server side)

**Comment by magsout** [comment]
ou alors on utilise `use`  ?

**Comment by MoOx** [comment]
Naaan c'est relou. On inline comme des cochonnes. Ca marche bien !
Et t'as pas de bug(s) de merde sur safari ou autre.
`use` ça veut dire que tu génères un sprite toussa, ça n'apporte pas grand chose finalement. Nos petits svg c'est que un peu de texte :)

**Comment by magsout** [comment]
Top la méthode que tu as utilisé pour inline les SVG, effectivement ça évitera les bug de `use` par contre, je n'ai jamais utilisé cette méthode, mais un sprite n'est pas necessaire, j'ai rien vu dans le doc, qui disait ça

**Comment by MoOx** [comment]
Bah use c'est pour faire référence à un id dans un svg, donc ça veut dire que t'as un gros svg avec tous tes icones dedans (c'est une sorte de sprite donc).

**Comment by lionelB** [comment]
C'est quoi le bug du use (pour ma culture perso) ?

**Comment by lionelB** [comment]
en regardant le code de SVGICon je me suis demandé si on pouvait pas utilisé ça https://github.com/rpominov/svgo-loader ?
(désolé si ça à l'air con, j'ai un peu du mal avec webpack)

**Comment by MoOx** [comment]
bug avec use on onClick sur safari ou seul les click sur un path non transparent fonctionne. Plutôt pénible pour un bouton carré que seul la forme exacte de l'icone soit cliquable.

Le site actuellement n'utilise pas webpack pour le rendu via react, c'est pour cela que je n'ai pas utilisé de loader.
Webpack est utilisé pour le js côté client (encore très pauvre) et les css.

**Comment by lionelB** [comment]
merci pour ta réponse
