### ISSUE TITLE
gh token has been compromised

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#376]
ref https://github.com/X1011/git-directory-deploy/issues/7

**Comment by MoOx** [comment]
Donc le build en prod ne marchera pas tant que je n'aurais pas recrée de token. Je ferais ça à l'occassion.

**Comment by MoOx** [comment]
puisque j'ai tuer le token bien entendu.

**Comment by Nyalab** [comment]
token === :skull:

**Comment by MoOx** [comment]
Token has been update, so autodeploy is back.
I've also reported the accurate source of the leak and the author of the original script is working on a solution, so good news, we just need to wait to update the script and close this issue.

**Comment by Nyalab** [comment]
wooot :clap:
