### ISSUE TITLE
Urls du feed dans les contenus sont incorrecte

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#379]
- les urls des ancres sont pas bonnes
- les urls des images sont pas bonnes
etc.
Tout ce qui est relatif n'est pas bon. Et c'est pas nouveau de mémoire.

**Comment by madx** [comment]
J'aimerais travailler là dessus mais je comprends pas le titre de l'issue :/ Tu peux donner un peu plus de détails ?

**Comment by MoOx** [comment]
en gros dans le feed, les urls des assets (images par exemple) sont pas bonne puisque relative au post
Un post est normalement dans /posts/truc/machine/index.html et ses assets potentiellement dans /posts/truc/machine/* et dans le post les assets utilises des adresses relatives (donc en ./).
Pour le rss du coup (où les contenus sont à plat) les urls ne sont pas ajustés et comme le feed est à la racine du site, ça nique les images. Tu n'as qu'à ouvrir le feed et tu vera les 404 dans ta console (genre avec firefox).

**Comment by madx** [comment]
Ok j'ai saisi, j'vais voir ce que je peux faire

**Comment by madx** [comment]
Bon, y'a 2 solutions:

- Soit on réécrit le XML pour remplacer les URLs relatives correctement via un petit plugin metalsmith
- Soit on utilise des attributes `xml:base`, mais tous les lecteurs de flux ne le supportent pas

Perso je vote pour la première méthode même si ça implique + de code et un peu + de temps de processing.

**Comment by MoOx** [comment]
Je devrais le gérer dans metalsmith-feed en fait.

**Comment by MoOx** [comment]
metalsmith-rss* (package de moi)

**Comment by madx** [comment]
Je vais commencer par écrire le plugin en dur dans putaindecode.fr puis je te fais une PR dans metalsmith-rss oui

**Comment by madx** [comment]
@MoOx tu peux essayer de modifier le build.js comme ça et me dire ce que tu en penses ?

``` javascript
  .use((files, metalsmith, done) => {
    const metadata = metalsmith.metadata()
    const collection = "posts"
    const limit = "1"
    const collectionItems = metadata.collections[collection].slice(0, limit)

    collectionItems.forEach((item) => {
      const contents = item.contents.toString()
      const contentsWithAbsoluteUrls = contents.replace(/href="([^"]+)"/g, (match, url) => {
        return (url.match(/^[a-z]+:\/\//) !== null) ?
          match :
          `href="${item.route + url}"`
      })
      item.contents = new Buffer(contentsWithAbsoluteUrls)
    })

    return done()
  })

  .use(
    rss({
      feedOptions: {
        title: i18n.title,
        site_url: pkg.homepage,
        language: "fr",
        categories: [
          "code",
        ],
      },
      destination: "feed.xml",
    })
  )
```

**Comment by MoOx** [comment]
Not bad. A good start.
This will need to be applied to src too not just href (image/iframe etc) and also using item.url and not route since we will remove those. I will do that tomorrow and reuse the code you posted. Maybe we can even make a metalsmith-absolutize-urls to do that. What do you think ?

**Comment by madx** [comment]
Yeah I'm not that much happy with the code quality and the covered cases

I think extracting to a separate plugin is the way to go, with a parameterizable base URL and replacement patterns.

Also, maybe we should avoid using regexen and use a real XML parser (a SAX one preferably) but I'm not that comfortable with XML parsing in io.js so I have to check what options are available

**Comment by MoOx** [comment]
wot lel no.
Hum maybe we should just handle that in the markdown transformation ?
Yeah I will try from here and see if the code is lighter.

**Comment by MoOx** [comment]
I would like to avoid a xml parsing on each page !

**Comment by madx** [comment]
Maxime I think I have a better idea

We can override marked's link rendering to automatically add the absolute URL, and put that override mechanism as a plugin when rendering the feed. This is the cleanest way imho

**Comment by MoOx** [comment]
THat what I where thinking. I am on ti.

https://github.com/chjj/marked#inline-level-renderer-methods

**Comment by madx** [comment]
Good :)

**Comment by MoOx** [comment]
Ok we can't just do that with marked since we don't have access to the path in the current scope of rendering. Fallback to first solution.

**Comment by MoOx** [comment]
Eventually I found a way to pass the context to marked. Much better an reliable way.
I will push that after some tests. This will allow us to have all urls with full absolute urls (including domain) in order to provide reliable standalone rss feed.

**Comment by madx** [comment]
I knew it was possible :-)
Le 14 mai 2015 7:45 AM, "Maxime Thirouin" <notifications@github.com> a
écrit :

**Comment by madx** [comment]
Nickel !

**Comment by magsout** [comment]
:+1:
