### ISSUE TITLE
supprimer les routes dans les fichiers md

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#380]
Ca sert à rien au final.

**Comment by Macxim** [comment]
Juste dans les posts ou dans tous les .md ?

**Comment by bloodyowl** [comment]
je continue à penser que ce serait plus flexible de laisser le post décider de son URL dans la config.
ça permet de développer des trucs naifs par rapport au file-system.

**Comment by Macxim** [comment]
Je viens de me rendre compte que ma question était débile en fait. Il n'y a que dans les posts qu'il y a des routes. Bon à part `/projets/index.md` et `/c-est-quoi-putaindecode/index.md`.

**Comment by bloodyowl** [comment]
up https://github.com/putaindecode/putaindecode.fr/pull/381

**Comment by bloodyowl** [comment]
pour résumer, je pense qu'il faille garder (je sais pas si on peut s'en servir avec metalsmith) la route dans la vue, parce que le jour où on s'en débarrasse, j'aimerai autant qu'on puisse générer des pages avec un input dont la source nous importe pas.

si on se cale sur le file-system, on a *potentiellement* des soucis de casse, l'impossibilité (ou complexité non-nécessaire) de reorganiser les directories et un parallélisme obligatoire entre les sources et l'output, ce qui me semble absolument pas être une bonne idée.

**Comment by MoOx** [comment]
On pourrait s'en servir avec metalsmith, faudrait faire un plugin de 5 lignes.
Je comprend ton point mais les contres arguments:
- conflit possible entre 2 posts qui aurait la même url (pas pire que la casse)
- gros bordel possible entre l'organisation des posts sur le fs et les urls qui n'ont rien à voir

L'output n'est qu'un resultat d'un process que l'on controle. Si on veut faire des routes dynamiques en fonction du nom et controler que y'a pas de conflits (de casse?) on peut le faire très facilement.

- la casse est un faux problème: si t'es sur un fs non sensible tu peux pas créer de doublon (DouBlon) (donc pas de problème). Puis si un mec sur un fs sensible le fait, le premier qui va pull sur un fs non sensible va pleurer.
- réorganiser les dossiers/posts c'est possible, il suffira d'avoir une map pour le seo (htaccess ou merde dans le genre). Et si on reste sur gh, on peut générer des pages de redirections facilement.
- le parallelisme entre les sources et l'output je trouve que c'est une bonne chose, ça évite de se demander "où est ma page". Je vois pas trop le problème de ce point.

**Comment by Nyalab** [comment]
je suis ok avec @MoOx pour ce sujet, si jamais on veut faire un truc custom, on fera un objet de mapping au pire, sinon ça va être le bordel en pratique

**Comment by MoOx** [comment]
J'aimerais l'input de d'autres membres. On se sent un peu seul pour décider des fois.

**Comment by lionelB** [comment]
du meme avis que @MoOx et @Nyalab

**Comment by madx** [comment]
Ça existe encore les FS non-sensibles à la casse ? :hankey: 

Je pense qu'il vaut mieux être cohérent entre le nom du fichier et la route du post donc ne pas avoir de double information à ce sujet : le nom du post => la route

**Comment by kud** [comment]
@madx c'est une option que tu précises dans unix/linux donc oui. Et je ne sais guère ce qu'il en est de Windows.

**Comment by MoOx** [comment]
Majority wins :/
