### ISSUE TITLE
watcher cache invalidation doesn't work on iojs

### ISSUE THREAD

**Issue by Nyalab** [putaindecode/putaindecode.fr#382]
[this test](https://github.com/putaindecode/putaindecode.fr/blob/master/scripts/metalsmith/server/__tests__/watcher.es#L154) fails for me.

the content of the file remains `1`. I tried to fix it but did not succeed. I don't know how the watcher is working, i think the problem comes from it.

**Comment by MoOx** [comment]
can you try to increase the timeout that wrap this test plz ? are your using an SSD or a HDD ?

**Comment by Nyalab** [comment]
yes, i should had written that in the original issue, i tried to increase it to 10s ; i have got a ssd one.

**Comment by MoOx** [comment]
ok...
I guess you use iojs ?

**Comment by Nyalab** [comment]
yes, what do you want me to try ?

**Comment by MoOx** [comment]
dunno. I guess the cache for iojs have got some changes. So I dunno what to do. We should take a look to iojs doc if any to make this function work https://github.com/putaindecode/putaindecode.fr/blob/master/scripts/metalsmith/server/watcher.es#L16-L21

**Comment by Nyalab** [comment]
hmmm ok, i see, i will take a deep look when i have the time for it. at least it does not fail for the majority of people :smile:

**Comment by MoOx** [comment]
Closed by b0b29af9b6ec836d2171bad1d82d7a2c02e7cdf6

(it's working on iojs now, see https://travis-ci.org/FWeinb/metalsmith-watch)
