### ISSUE TITLE
déclaration doctype absente

### ISSUE THREAD

**Issue by Reeslo** [putaindecode/putaindecode.fr#390]
https://validator.w3.org/check?uri=http%3A%2F%2Fputaindecode.fr%2F&charset=%28detect+automatically%29&doctype=Inline&group=0

![screen](https://cloud.githubusercontent.com/assets/2724844/7495199/b9e672e2-f40c-11e4-9902-831fb1a71e9d.png)

**Comment by bloodyowl** [comment]
thanks for the head's up. @MoOx do you want to add this? I'll do it otherwise

**Comment by MoOx** [comment]
I will handle that in metalsmith-react. Done here. I have to publish and use the update
