### ISSUE TITLE
boitenoirekiller

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#391]
On met ça ? http://boitenoirekiller.com/

**Comment by kud** [comment]
Je suis plutôt pour mettre un message d'explication de ce qu'est la loi et en quoi elle est néfaste qu'une pratique comme ça.

**Comment by MoOx** [comment]
Tout le monde a déjà bien assez publié sur le sujet. Il faut agir.
Après ça c'est une idée si elle vous plait pas tant pis.
C'était pour déconner un peu.

**Comment by kud** [comment]
Je ne suis pas sûr que cela soit efficace, et la loi n'est pas encore appliquée. Il y a encore le sénat, etc.

**Comment by MoOx** [comment]
> C'était pour déconner un peu.

**Comment by kud** [comment]
Tu demandes mon avis.

**Comment by madx** [comment]
Bref :no_entry:

**Comment by Nyalab** [comment]
j'ai pas d'avis :neutral_face:

**Comment by bloodyowl** [comment]
j'm'en bats les couilles

**Comment by MoOx** [comment]
🐬🐬🐬
