### ISSUE TITLE
iojs will be mandatory

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#398]
I am going to use jsdom for fast module testing during dev and latest version doesn't work with node anymore.
I think this situation is just a start, so we are going to force iojs.
Are you all ok with that ?
(Note: I recommand nvm)

**Comment by kud** [comment]
What the interest for the moment? How many people use iojs?

**Comment by bloodyowl** [comment]
I'm ok with it.

**Comment by MoOx** [comment]
@kud jsdom 4 only works on iojs.
Also iojs is semver compliant.

**Comment by kud** [comment]
We could have a try but forcing iojs I don't know if it's a good idea. Let's see what happens with nvm so.

**Comment by MoOx** [comment]
Closed in favor of #389 

Seriously, nodejs is so slow now, we can't say the opposite.
iojs is already 2.0... with already 26 releases !

**Comment by kud** [comment]
Slow in which way? performance or just updates? Because in my opinion it's not a race.

**Comment by MoOx** [comment]
Slow for merging/releasing & fixing issues.
More and more people switch to iojs each day. We should too.
@Nyalab already use it everyday for some times without any issue.

**Comment by kud** [comment]
Okay, cool so.

I was wondering if I should switch or not. I think I'll use iojs so and let's see what happens.

**Comment by Nyalab** [comment]
slow in performances, slow in its release cycle ; go for io.js, just install it, you won't see the differences since everything still works and, much faster
