### ISSUE TITLE
Proposition de post: "the dark side of postcss (awesomeness)"

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#403]
Postcss c'est bien. Mais attention, trop de postcss tue le postcss.

Il s'agirait d'un article sur la connerie que font de plus en plus de gens: faire leur preproc custom "modulaire". Ouais c'est bien jolie toussa mais voilà le bordel des css à la fin.

Vous imaginez si on faisait tous des syntaxes js custom avec acorn/babel ?
Des coffeescripts like non documenté, avec du freestyle de partout ?
Lel no.
C'est ce que postcss est en train de faire. Et oh mon dieu, c'est horrible.

(bon au final je vais surement dire que postcss c'est quand meme cool mais que faut (imo) pas l'utiliser directement, puis montrer cssnext et stylelint en exemple)

Je ferais ce post en 2 langues si vous pensez comme moi que bonjour la galère dans 2 ans quand tout le monde aura "ces css custom" (coucou mokoloko ^^).

**Comment by kud** [comment]
+1

**Comment by magsout** [comment]
>Il s'agirait d'un article sur la connerie que font de plus en plus de gens: faire leur preproc custom "modulaire". Ouais c'est bien jolie toussa mais voilà le bordel des css à la fin.

Genre utiliser des plugins pour palier à un manque du w3c et d'un coup utiliser des plugins à la Sass ? Mélanger pure css avec du css de programmation qui finalement te fait réinventer un nouveau pseudo language ?

**Comment by MoOx** [comment]
Bah ouais, finir avec un langage "custom" probablement non documenté, les nouveaux seront perdu etc...

**Comment by magsout** [comment]
:+1: tu préches un convaincu, donc faut en convaincre d'autre. NORMALIZE ALL THE THINGS

**Comment by MoOx** [comment]
je pense que faire une comparaison avec un truc genre "vous imaginez si on faisait ça avec javascript ? un mélange de coffee + es6 completement freestyle ? Ou sont les specs ? Je vous le demande !" ?

**Comment by lionelB** [comment]
Hello

Qu'est ce que tu entends par faire un preproc custom "modulaire" ?
Sinon, en relisant ton intro, j'ai l'impression que le principal argument de pas faire des prépro custom repose seulement sur le fait que se sera forcément mal fait 
> Des coffeescripts like non documenté, avec du freestyle de partout ?
Est ce qu'il y a des raisons où faire un prépro custom se justifie ?
Quelles serait las autres raisons de pas en faire ?

**Comment by MoOx** [comment]
Les standards monsieurs.

Fair un préprocesseur custom avec des syntaxes de l'espace c'est pas bon sur le long terme. Un nouveau sur un projet il arrive et devrait apprendre les spécificités de chaque module. Bon en soit c'est pas le pire des arguments. C'est plutôt l'aspect ci après qui me dérange.

Coffreescript, comme Sass est une sorte de standard propriétaire à leur façon.
Par contre des preproc "custom" qui utilise des étranges plugins pour ajouter des trucs complètements non standard voir dégeulasse (cf postcss-css-variables qui malgré son nom qui ressemble à la specs des variables css, a des comportements complètement perché qui n'ont rien à voir avec la spec) c'est juste mauvais et dangereux.

C'est un peu comme si un mec faisait un babel like mais que l'opérateur spread il fasse un deep clone plutôt qu'un passage de référence premier niveau. Vous voyez le délire ? Bah c'est un peu ce qui se passe, pleins de gens se mettent à piocher des plugins postcss et faire des trucs dans tous les sens.

Babel c'est standard, (tout comme cssnext - autopromo mais c pas du tout le but). Si par contre un mec prends esprima et qu'il se code tout un tas de plugin pour booster la syntaxe JS avec des trucs non standards vous serez d'accord que c'est pas top. 

Un cas isolé c'est pas grand chose, mais quand t'as un bon niveau de fragmentation...

Heureusement (attention au lol), le mec derrière postcss va faire un "postcss-lang" pour standardiser un peu tout ça. Un sass like quoi (ahem).

**Comment by MoOx** [comment]
Bon ben voilà je crois que mon post est quasiment terminé. Merci :)

**Comment by magsout** [comment]
NOMALIZE ALL THE THINGS

**Comment by MoOx** [comment]
Bon je ne prendrais pas le temps d'écrire ce post. Cela étant dit il y aura une section dans l'esprit dans la FAQ de cssnext.io.
