### ISSUE TITLE
`package.json` uses a git:// url for caniuse-api

### ISSUE THREAD

**Issue by madx** [putaindecode/putaindecode.fr#405]
Les URLs en `git://` sont peu pratiques à utiliser derrière un firewall restrictif.

On pourrait la remplacer par une URL `https://`.

J'ai fait le patch, j'attends vos avis. D'ailleurs j'en profite mais @Nyalab la branche de `caniuse-api` qu'on utilise ne pourrait pas être mergée dans le master ?

**Comment by MoOx** [comment]
@madx nan c'était un test cette branche. Tu peux utiliser la version ^1.3.1  ça marche pareil. De plus cette branche ne marche pas sur windows.

**Comment by kud** [comment]
Tant que ça demande pas un compte github quand tu lances le npm install. J'ai pas testé sur des repo publics, ça doit pas poser de souci mais en privé, c'est lourd, c'est pour ça que chez nous on a laissé git+ssh.

**Comment by madx** [comment]
Ok donc je vais essayer de passer sur ^1.3.1 et lancer un build en local

**Comment by madx** [comment]
On s'en sert pour quoi au fait ? :)

**Comment by MoOx** [comment]
Hah na mais en fait
je suis con.
Tu peux la virer
et reinstaller cssnext. Et ça passera.

**Comment by madx** [comment]
Lol je refais un npm install sans caniuse-api alors

**Comment by MoOx** [comment]
ouais fait ça. En fait c'est lié à ça https://github.com/Nyalab/caniuse-api/issues/29 mais j'ai aucune preuve exacte que ça soit lié à ça. C'est pour ça que su travis j'ai mis les npm install log.
Ca bloque "des fois" après ce package mais rien de sur.

**Comment by madx** [comment]
Bon, j'ai pas assez de ram pour tester sur mon chromebook L O L

**Comment by MoOx** [comment]
lelwat ? C'est une blague ? Enfin j'imagine que non. Etonnant.

**Comment by kud** [comment]
hardcore developer

**Comment by madx** [comment]
J'ai firefox (2 gmail + github + d'autres onglets) + chromium d'ouverts, ça doit déjà bouffer 75% de la RAM lol
