### ISSUE TITLE
Mise en avant (ou pas) des posts

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#407]
Ref https://github.com/putaindecode/organisation/issues/34
Faire des essais avec des étoiles en quoi, sur avatar ou post (preview) directement

**Comment by magsout** [comment]
Utiliser une forme simplifiée du logo pour dire member of p! et donc post approved by p! ?

**Comment by MoOx** [comment]
J'attends un petit screenshot pour voir ce que ça pourrait donner :)

**Comment by magsout** [comment]
C'est pas terrible

![approved](https://cloud.githubusercontent.com/assets/1997108/7661174/bb63f82e-fb50-11e4-9c79-e7ec3786c20d.png)

**Comment by MoOx** [comment]
Pas fan en effet.
Si tu tentes un truc simple genre border rouge sur l'avatar ?

**Comment by magsout** [comment]
Quelques tests comme ça : 

![p proposition 1 point d exclamation](https://cloud.githubusercontent.com/assets/1997108/8075412/886ca6ce-0f40-11e5-9882-73b7d6d579e7.png)
![p proposition 2 bord rouge](https://cloud.githubusercontent.com/assets/1997108/8075413/886ead48-0f40-11e5-9ad5-381adc88d015.png)
![p proposition 3 bord rouge decale](https://cloud.githubusercontent.com/assets/1997108/8075416/8870c150-0f40-11e5-902e-c8aac99bc661.png)
![p proposition 4 bord gris](https://cloud.githubusercontent.com/assets/1997108/8075414/886ec094-0f40-11e5-93fa-9300a2dbca97.png)
![p proposition 5 parenthese](https://cloud.githubusercontent.com/assets/1997108/8075415/886efcb2-0f40-11e5-9eae-cbe581e690cb.png)
![p proposition 6 double parentheses](https://cloud.githubusercontent.com/assets/1997108/8075417/888562fe-0f40-11e5-9bdc-a834bacde4ff.png)
![p proposition 7 double parentheses fines](https://cloud.githubusercontent.com/assets/1997108/8075418/8886d620-0f40-11e5-9010-d5f0861920f0.png)

**Comment by MoOx** [comment]
Le rond rouge à la limite, le reste j'ai du mal perso

**Comment by magsout** [comment]
Je suis pas fan non plus. A vrai dire je suis même pas sur que les gens fassent bien la distinction entre post fav et non fav. Je vais tourner ma réflexion ailleurs

**Comment by Macxim** [comment]
Pareil que @MoOx, le cercle rouge avec le petit espace blanc. Le reste, non.

**Comment by kud** [comment]
Au mieux https://cloud.githubusercontent.com/assets/1997108/8075416/8870c150-0f40-11e5-902e-c8aac99bc661.png.

Le reste, je n'aime pas. C'est trop grossier à mon sens. Mais j'aime bien l'idée.

**Comment by bloodyowl** [comment]
sinon on met rien hein

**Comment by kud** [comment]
On rajoute une étoile devant ou après chaque auteur membre ?

**Comment by lionelB** [comment]
rien pour ma part

**Comment by magsout** [comment]
>sinon on met rien hein

voila

**Comment by Macxim** [comment]
On close alors ?

**Comment by MoOx** [comment]
Dans un sens, les posts sont validés par la communauté, donc bon... Je ferais peut être une PR avec une étoile vite fait un jour...
