### ISSUE TITLE
Put post "hero image" in metadata in order to remove them from feed

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#409]
Not sure what is the best way, but some posts have big pictures at the top just to look good.
We should avoid them in the feed.
Setting image url as a metadata might and image should be rendered after rss (probably in react templates).

- http://putaindecode.fr/posts/entreprendre/auto-entrepreneuriat-retour-experiences/
- http://putaindecode.fr/posts/windows/comment-coder-sous-windows/

That would also make upgrade of the design easier (if we want to play with hero images).

**Comment by madx** [comment]
I agree that this could be put in a meta to choose how we display it

However, pourquoi on fait des issues en anglais ici en fait ?

Non la vraie question c'était : en quoi ça gène dans le flux ? Plein de flux le font et je trouve que ça fait partie intégrante du post

**Comment by MoOx** [comment]
Je t'avoue que je suis pas fan du rendu

![screen shot 2015-05-14 at 09 50 17](https://cloud.githubusercontent.com/assets/157534/7628074/d09d8d96-fa1e-11e4-921c-392924ea610f.jpg)

**Comment by MoOx** [comment]
Pour l'anglais moi c'est par habitude sur github, mais aussi https://github.com/putaindecode/organisation/issues/39

**Comment by madx** [comment]
Oui c'est pas faux, mais il me semble qu'on faisait exprès de faire des issues en français pour baisser la barrière d'entrée aux contribs

Anyway, pour le hero header LOL je vois ce que tu veux dire :-) On pourrait pas y foutre un style en dur?

**Comment by MoOx** [comment]
Oui mais bon ça va 2min les gens... A NOUS LA RENOMMÉ INTERGALACTIQUE. Pardon.

Pourquoi pas. Mais cela dit je pense que de toute facon faut faire 

1/ meta (-> plus flexible pour tout upgradé si changement de design)
2/ le rendu dans le flux devrait être différent du rendu du site (petit difficulté à gérer ça, rien de compliqué mais "faut le faire".
ou 2/ virer du flux (problem solved).

C'est image c'est comme medium, c'est gentil mais ça sert vraiment à rien, surtout dans un feed je pense.
A là limite les rss ont pas de metadata pour définir des thumbnails ? On l'y passerais dedans et on la gère plus dans le rendu du post (sauf sur le site via les templates).
