### ISSUE TITLE
Ensure title anchor are unique

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#410]
https://github.com/putaindecode/putaindecode.fr/blob/master/scripts/marked.es#L93
Since we use text, we might get the same anchor twice. We should fix that by adding a simple incremented integer.
Bug is visible on this page http://putaindecode.fr/posts/entreprendre/auto-entrepreneuriat-retour-experiences/

**Comment by madx** [comment]
You might want to look how pandoc does for unique identifiers

http://pandoc.org/README.html#extension-auto_identifiers
