### ISSUE TITLE
Write a document about how to contribute

### ISSUE THREAD

**Issue by madx** [putaindecode/putaindecode.fr#412]
As of now we have multiple sources with documentation about how to contribute:

- `README.md`
- `CONTRIBUTING.md`
- http://putaindecode.fr/posts/comment-contribuer/

All three of them are mostly out of date at some different levels.

We need to have a single source of information about how to contribute. This could however be splitted between `README.md` (used mostly for technical & quick start instructions) and `CONTRIBUTING.md` for post writing guidelines.

**Comment by MoOx** [comment]
I think the more we can push on the website (in i18n) the better it is.

Related issues https://github.com/putaindecode/putaindecode.fr/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+doc%22

**Comment by Nyalab** [comment]
i don't think this is a matter, README for people browsing the git repository, CONTRIBUTING because it is linked when you open a new issue and for used-to-tech-and-github people, the website post for "other people"

but i agree we should find a way to "sync" them, or to update them now
