### ISSUE TITLE
Proposition de post : "Introduction à cssnext"

### ISSUE THREAD

**Issue by Macxim** [putaindecode/putaindecode.fr#422]
Il est temps de le sortir je crois.

**Comment by MoOx** [comment]
Faut voir avec thedotpost comment on fait. Sinon on garde en/fr pour ici ?!

**Comment by MoOx** [comment]
Mais sinon ouais.

**Comment by magsout** [comment]
D'ailleurs c'est prévu pour quand chez eux ?

**Comment by MoOx** [comment]
Bah justement. Je me demande si on garde pas tout ici. Le trafic de ce site à l'air juste nul (aucun pic sur le site de cssnext par exemple lié à la vidéo)

**Comment by magsout** [comment]
De toute manière y a pas d'exclu chez eux ? Moi je suis pour tout publier ici. L'article de @Macxim est top en EN comme en FR

**Comment by MoOx** [comment]
Ouais mais du double contenu ça sert à rien. On va faire un PR chez eux pour le virer.
@Macxim t'as qu'à fermer ta PR de correction. Je fais une PR chez eux.

**Comment by MoOx** [comment]
On verra ce qu'il dit...

**Comment by MoOx** [comment]
https://github.com/thedotpost/thedotpost-content/pull/3

**Comment by Macxim** [comment]
Oui, faisons ça.
Ça fait deux semaines que c'est chez eux et que ça ne bouge pas.
Aucun intérêt.

**Comment by MoOx** [comment]
Après je comprends qu'il ne sorte pas le post en même temps que l'autre et qu'il attende hein. Mais vu qu'on va push du contenu en asap, autant garder ce contenu (de chez nous) chez nous :)

**Comment by Macxim** [comment]
J'ai aussi une version ES qui est prévue. Ça peut toujours servir.

**Comment by MoOx** [comment]
Pour l'image on pourrait choisir par là

https://www.flickr.com/search/?license=4%2C5%2C6%2C9%2C10&text=back%20to%20the%20future&advanced=1 (license ok)
ou prendre celle là p-e :D http://the--kyza.deviantart.com/art/What-the-Flux-511691704

**Comment by Macxim** [comment]
J'avoue que celle-ci est top :)
