### ISSUE TITLE
Post minimal guidlines

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#426]
Je propose qu'on se fasse des guidlines pour la rédaction de posts. Chaque post devra respecter ces règles:

- Un post ne doit pas contenir de formule personnel ("Je pense que", "je vous nique tous avant la mise en prod le vendredi" etc). Une des raisons _selon moi_ (BAM ça passe pas ça par exemple). Puisque revu et corrigé par une groupe -- parenthèse: dans ce sens, on devrait diminuer la taille du bloc de l'auteur en fin de post, car au final, le lecteur s'en branle de qui c'est qui écrit nan ?

En fait je comptais en mettre plusieurs, mais j'ai l'impression que la règle ci dessus ferait indirectement beaucoup de bien sur les formulations du genre "j'encule les nazi et les pd", puis ça devrait être écrit "On encule..." et que à la revu il faut un minimum d'approbation. 

Ma règle je l'aime bien sans y avoir trop réfléchi car à elle toute seul, elle préviendrait pas mal de choses.
Vous avez le droit de faire à la @Nyalab: :+1: ou :-1:  ou éventuellement :fuck: ou :ragequit:

Je viens de penser à ça aussi

- En cas de "litige", on doit revoir un point si plus de la moitié des personnes qui s'expriment pensent que le point en question mérite d'être revu à raison d'un minimum de 3 personnes.

Ca reste simple et pas contraignant (j'ai pas dit genre si plus de 1 sur 10 :D)

**Comment by kud** [comment]
DÉSOLÉ SI JE RÉPONDS PAS TOUT DE SUITE, FAUT QUE JE RÉFLÉCHISSE CORRECTEMENT AU SUJET.

**Comment by MoOx** [comment]
Transféré https://github.com/putaindecode/organisation/issues/41
