### ISSUE TITLE
Owners definition

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#427]
on pose la chose suivante : 

owners = 8 top contribs (contrib: commit + issue comments) sur les 12 derniers mois en date des noms de domaines.

C'est simple et ça évite de demander et on a aucune rancune à retirer les inactifs des owners.

:+1: or :-1:

**Comment by Nyalab** [comment]
:+1:

**Comment by kud** [comment]
:-1:

**Comment by MoOx** [comment]
on poserais*. Ceci n'était pas un choix. Mais je sens sur le chat que mes points soulèvent des problématiques que je voudrais éviter à tout prix: la prise de tête.

**Comment by MoOx** [comment]
Transféré https://github.com/putaindecode/organisation/issues/42
