### ISSUE TITLE
Minimal requirement for hero image

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#436]
2 things that should be done (I think) before adding in git

- max width 2048
- compress with jpeg mini (light) (app store) - ~really~ good jpeg compressor (best I found so far)

This will ensure us to have a small repo, even with lots of images (I think)

Any thoughts ?

**Comment by MoOx** [comment]
And btw, here is a nice link to find images

**Comment by kud** [comment]
I don't mind about the size, it's mostly the weight which is important in my opinion.

Yes we should optimise images in any case.
