### ISSUE TITLE
Add a markdown linter

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#438]
Some rules
- max length for lines
- some basic check for links & headings

https://github.com/DavidAnson/markdownlint

**Comment by lionelB** [comment]
:+1: good idea
 I guess it will improve the diff & review

**Comment by magsout** [comment]
Yep top

**Comment by Nyalab** [comment]
nice idea!

**Comment by Macxim** [comment]
We definitely need this.

**Comment by MoOx** [comment]
Closing in favor of #452
