### ISSUE TITLE
Some search engines fail to get a correct description for the website

### ISSUE THREAD

**Issue by magsout** [putaindecode/putaindecode.fr#441]
![capture d ecran 2015-06-10 a 07 06 42](https://cloud.githubusercontent.com/assets/1997108/8075322/4ee880cc-0f3f-11e5-8026-7627071a47f3.png)

**Comment by MoOx** [comment]
Bizarre car Google resort pas du tout ça...

**Comment by magsout** [comment]
Yes,  y a même les site link sur Google

**Comment by Macxim** [comment]
J'ai hacké le canard avec ma description !

**Comment by Macxim** [comment]
Même chose ici : 
![screen shot 2015-06-11 at 10 48 20 am](https://cloud.githubusercontent.com/assets/1909957/8103273/714b14fc-1027-11e5-8e42-f31ec7891f08.png)

Et ici : 
 
![screen shot 2015-06-11 at 10 49 35 am](https://cloud.githubusercontent.com/assets/1909957/8103291/a2f57d30-1027-11e5-9df4-94126f5e36ba.png)

**Comment by kud** [comment]
Un meta description aiderait peut-être.

**Comment by Macxim** [comment]
Oui, je viens de voir qu'il n'y en avait pas.

**Comment by MoOx** [comment]
les meta desc et keyword c'est juste la loose. Faut plutôt comprendre pourquoi ça merde précisément là sur plusieurs moteurs.

**Comment by magsout** [comment]
`keyword` c'est useless, et utilisé par aucun moteur de recherche .

Par contre la meta description ou item description, c'est un peu le but pour les moteurs de recherche. Je vois pas d'autre raison du bug @MoOx ?

**Comment by MoOx** [comment]
Les moteurs de recherches devrait prendre le texte sémantiquement le plus important. Là il prends juste un truc random au milieu d'une liste. Faut surement qu'on revoit l'html de la page et ça suffira imo.
J'ai juste jamais eu à utiliser une desc depuis plusieurs années.
De plus selon ta query, le moteur peut resortir un bout de texte en plein milieu de la page si c'est ça qui match, donc les meta desc c'est une perte de temps selon moi.

**Comment by kud** [comment]
Si on arrive sans, c'est cool mais dans l'idée, je pense que la meta description est importante pour le SEO et ce genre de problème. Dans n'importe quelle boite où j'étais, on la mettait.

**Comment by MoOx** [comment]
Alors mettez là, je vous en prie :)

**Comment by kud** [comment]
Je vais en mettre une statique provisoirement, et on ajustera en fonction des pages.

**Comment by MoOx** [comment]
Closed by a16e23e2ada3e56de5d4e78b5da0b12dae618d23
