### ISSUE TITLE
Bug cover d'un article en version mobile sur iphone 4

### ISSUE THREAD

**Issue by cedricdelpoux** [putaindecode/putaindecode.fr#454]
Lorsque j'essaie de visionner un article depuis un iphone 4, la photo de couverture de l'article est immense et il me faut scroller assez longtemps pour pouvoir lire l'article.

![image 1](https://cloud.githubusercontent.com/assets/2683300/8178728/5cf5cb58-1411-11e5-8c6c-639b8c8b808e.png)
![image](https://cloud.githubusercontent.com/assets/2683300/8178727/5cf23ede-1411-11e5-8374-765386b0f80c.png)

**Comment by magsout** [comment]
@cedricdelpoux  iPhone 4 avec iOS 7?

**Comment by cedricdelpoux** [comment]
@magsout iOS 7.1.2 
On ne peut pas aller au delà sur un iPhone 4

**Comment by magsout** [comment]
Sur le smiluator ça passe nickel. T'as essayé de supprimer ton cache ? Ca fait ça sur tous les posts ?

**Comment by MoOx** [comment]
Quel browser ?

**Comment by Macxim** [comment]
Pour information, j'ai remarqué un truc étrange sur iPhone 5, Safari, iOS 8.3.
L'image ne s'affiche pas correctement non plus.
![img_5872](https://cloud.githubusercontent.com/assets/1909957/8180128/2316b298-141c-11e5-9605-22dd935aef12.PNG)

**Comment by magsout** [comment]
@Macxim exact , je viens de faire le test. Un refresh et l'image se load seulement après

**Comment by MoOx** [comment]
J'ai testé que sur ff en faisant ça :trollface:

**Comment by MoOx** [comment]
@Macxim same issue as you reported on iPhone 4s/iOS 8.x on iOS Simulator.

**Comment by cedricdelpoux** [comment]
On dirait que ça le fait que pour l'article sur docker chez moi

**Comment by MoOx** [comment]
I use 15vh for the header and it seems iOS 7 is pretty buggy with it http://stackoverflow.com/questions/28139752/ios-vh-on-viewport-orientation-change
I will use rem for small screen to avoid this... (I have a real iPhone 4 so I will fix it...)

**Comment by MoOx** [comment]
I pushed a fix, cannot reproduce both bugs atm

**Comment by Macxim** [comment]
J'ai encore le problème.

**Comment by MoOx** [comment]
sur iOS 8 donc ? cf ton screen ?

**Comment by Macxim** [comment]
Yep, exactement.

**Comment by magsout** [comment]
Le bug de @cedricdelpoux et @Macxim sont différents. @MoOx ton commit régle bien le problème de vh mal géré par iOS7. Pour l'autre, au premier chargement on a une partie de l'image mais par contre le fallback pour le brackground est bien présent sur toute la surface. Si on refresh la page, l'image se charge bien sur tout le header

**Comment by MoOx** [comment]
Ouais j'ai réussi à l'avoir une fois au début, après impossible à reproduire. Le vieux bug random de merde... Ça va être fun à fixer... Le `*zoom: 1` me manque des fois :D. Ah et `transform: translate3D(0,0,0)` ? :D

**Comment by cedricdelpoux** [comment]
Le bug est résolu chez moi en tout cas. Super réactivité les gars. Merci :+1:
