### ISSUE TITLE
Bug travis après avoir mergé dans master

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.fr#456]
- J'ai corrigé une typo sur un article
- J'ai mergé dans master
- J'ai rien fait de plus
- Travis a apparemment déployé son fail : 

![macosx-2015-06-16-at-10 36 41](https://cloud.githubusercontent.com/assets/655838/8179019/e217659c-1413-11e5-9563-5d84b4035e06.png)

Ce qui est drôle, c'est le nombre de commits (en haut à gauche de l'image :D). Quelle ironie du sort.

Apparemment @MoOx, d'après les logs slack, tu es au courant.

Là, je suis en train de déployer à la mano du coup.

**Comment by magsout** [comment]
ahaha le 404 fail ;p

**Comment by MoOx** [comment]
Le build cassé ne deploy plus https://travis-ci.org/putaindecode/putaindecode.fr/builds/66999338
