### ISSUE TITLE
Problème de contraste sur les citations ?

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.fr#459]
Avant : 

![macosx-2015-06-16-at-15 47 24](https://cloud.githubusercontent.com/assets/655838/8184486/0aa59e68-143f-11e5-96f6-bb7c71da83b6.png)

Après : 

![macosx-2015-06-16-at-15 49 08](https://cloud.githubusercontent.com/assets/655838/8184547/44e504d8-143f-11e5-8c67-9f5d27810d1b.png)

```css
color: #5A5A5A;
border-left: 0.25em solid #E8E8E8;
```

**Comment by kud** [comment]
J'ai éclairci la bordure pour bien indiqué que c'était une citation et j'ai asombri le texte pour une meilleure lecture.

**Comment by MoOx** [comment]
Je trouve qu'on voit plus assez la différence pour le coup.

![screen shot 2015-06-16 at 17 53 13](https://cloud.githubusercontent.com/assets/157534/8187555/a361aca8-1450-11e5-891c-1f0c3de044b0.png)

**Comment by kud** [comment]
Mon seul problème ici est que le texte est beaucoup moins lisible ou plutôt qu'il est trop mis "de côté" le rendant un peu "facultatif" à lire.

**Comment by MoOx** [comment]
Faut voir comment medium gère ça.

**Comment by kud** [comment]
![macosx-2015-06-16-at-18 06 14](https://cloud.githubusercontent.com/assets/655838/8187824/6d40e790-1452-11e5-9308-bbe09950b225.png)

https://medium.com/@ev/a-mile-wide-an-inch-deep-48f36e48d4cb

Apparemment la couleur est assez sombre quand même, par contre, italique.

**Comment by MoOx** [comment]
anéfé.

**Comment by magsout** [comment]
Je pencherais sur le coté medium. Même font, même couleur, même size, juste italic et le border.

**Comment by kud** [comment]
Je suis ok avec @magsout sauf éventuellement la fonte à voir, et surtout le border, je suis preneur de celui que j'ai proposé :D je l'aime bien. Attendez, je vais tester

> blablabla ça va vous ?

**Comment by kud** [comment]
Ouais le même border que Github en fait.

**Comment by kud** [comment]
Sur le nouvelobs :

![windows-2015-06-16-22 01 48](https://cloud.githubusercontent.com/assets/655838/8193171/7fa6e990-1473-11e5-8351-80e754d05f35.png)

(la ferme @bloodyowl, on s'en fout du contenu)

**Comment by kud** [comment]
En fait, le décalage + border en soit pourraient suffire.

**Comment by MoOx** [comment]
En fait je crois que j'avais tout pompé de github quand je l'ai fait de mémoire.

**Comment by kud** [comment]
Chez playtv, on fait ça. J'aime bien l'idée de la quote en background.

![windows-2015-06-16-22 04 49](https://cloud.githubusercontent.com/assets/655838/8193198/b7bdbcf0-1473-11e5-8dab-c92420319722.png)

**Comment by MoOx** [comment]
c super moche lol.
Go pour ta première modif. Je mettrais juste une couloir entre la tienne et l'existant pour le texte.

**Comment by kud** [comment]
Super moche ?

![1343594355-moche](https://cloud.githubusercontent.com/assets/655838/8193236/f899fff4-1473-11e5-9336-db380525a7e6.jpg)

---

Okay je ferai une PR et je vois ce que disent les gens. :)

**Comment by MoOx** [comment]
J'aurais mis ça plutôt

![](https://avatars3.githubusercontent.com/u/655838?v=3&s=512)

**Comment by kud** [comment]
Mais quel con :D

**Comment by MoOx** [comment]
Idem, PR si besoin, sinon on laisse des issues trainées.
