### ISSUE TITLE
Contraste sur le titre

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.fr#460]
Une remarque que je trouve juste sur twitter : https://twitter.com/nhoizey/status/610741580132171776

Je vais voir ce que je peux proposer.

**Comment by Macxim** [comment]
Oui, on l'a aussi évoqué ce matin sur Slack. Et puis il y a aussi https://github.com/putaindecode/putaindecode.fr/issues/429

**Comment by kud** [comment]
Okay on peut fermer ici alors.

**Comment by MoOx** [comment]
A noté que on peut mettre un gradient à la main par dessus l'image, ça a déjà été fait sur plusieurs posts

http://putaindecode.fr/posts/ci/le-deploiement-continu/
http://putaindecode.fr/posts/entreprendre/auto-entrepreneuriat-retour-experiences/

Ca ferait le taf en attendant (c'est indiqué dans le CONTRIBUTING.md ;))

**Comment by MoOx** [comment]
Je pense que on peut pas forcément mettre une couleur automatiqueemnt. C'est à l'auteur de gérer ça imo.

**Comment by kud** [comment]
Carrément @MoOx
