### ISSUE TITLE
Problème de line-height / padding sur les tags

### ISSUE THREAD

**Issue by kud** [putaindecode/putaindecode.fr#461]
Il n'y a pas le même padding en haut qu'en bas, est-ce voulu ?

![macosx-2015-06-16-at-15 56 28](https://cloud.githubusercontent.com/assets/655838/8184736/4ee5746c-1440-11e5-8db9-796b4ff3750f.png)

(Je ne fais pas de PR pour l'instant, je prends la tension. Si ça vaut le coup, je ferai en conséquence. ;))

**Comment by lionelB** [comment]
à droite et à gauche non plus on dirait :D

**Comment by MoOx** [comment]
PR si besoin, je ferme.
