### ISSUE TITLE
Proposition de post: utiliser Webpack pour gérer un thème Wordpress

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#475]
Petit post avec juste quelques petits tips pour se faire un petit workflow webpack pour un thème wordpress. Oui ou nan?

**Comment by madx** [comment]
Resiously, Wordpress ?

Je suis mitigé là :/

**Comment by MoOx** [comment]
Si tu as un autre CMS accessible que Wordpress pour du site administrable par madame ou monsieur tout le monde je suis preneur. À ce jour malheureusement, je n'ai trouvé mieux et aussi souple que ce bon vieux moteur. Et puis bon http://bethesignal.org/blog/2015/02/27/new-era-wordpress-hhvm-rest-react/

Le code de Wordpress est ce qu'il est à ce jour, ça n'empêche pas que la finalité est bien pratique (genre les auto mises à jour semver de patchs de sécu par exemple).

Cela étant dit, le post n'est pas "est-ce que wordpress c'est bien ou mal".

**Comment by madx** [comment]
Bah tu vois une fois bien argumenté comme ça je suis bien mitigé

:+1: pour du Wordpress moderne

**Comment by kud** [comment]
Je trouve justement qu'un post "poussé" (oui webpack ne doit pas être mass utilisé dans la communauté Wordpress, mais je me trompe peut-être) sur comment faire du wordpress et bien, ça a son intérêt.

**Comment by magsout** [comment]
Bon je veux bien. je vais devoir bosser sur webpack. Alors GOOOOO @MoOx

**Comment by MoOx** [comment]
pr incoming today.

**Comment by magsout** [comment]
:+1:
