### ISSUE TITLE
Slack page is not working

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#484]
https://putaindecode-slack.herokuapp.com/ seems dead atm. Need to check what is wrong.

**Comment by magsout** [comment]
We can replace directly by: https://putaindecode.slack.com/ no ?

Why we need the address on heroku ?

**Comment by MoOx** [comment]
The default page doesnt offer an invite form :(

**Comment by MoOx** [comment]
Should we remove slack from our homepage since we are considering Discord? :trollface:

**Comment by MoOx** [comment]
I tried to regenerate the app but it seems to be worst than before.

**Comment by MoOx** [comment]
Ok, it was slow but it's fixed.
