### ISSUE TITLE
Update "Top contributors" section to reflect a recent period of time

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#485]
Last 6 months (or maybe last year to avoid too few contributions) should be enough + limit to 8.

The idea behind is to have the "auto" list of the owners. Related to https://github.com/putaindecode/organisation/issues/42

What do you think?

**Comment by MoOx** [comment]
FYI, here are test with 6 months, then 12 months

```
~/Sync/Development/putaindecode/putaindecode.fr master*
❯ git shortlog --no-merges --summary --numbered --email --since 2015-04-18T19:56:13.769Z  
   197  Maxime Thirouin <...>
    36  Maxime Laforet <...>
     7  Uhsac <...>
     6  Guillaume Demesy <...>
     6  Erwann Mest <...>
     5  Sébastien Balayn <...>
     3  Enguerran <...>
     3  François Vaux <...>
     ...

~/Sync/Development/putaindecode/putaindecode.fr master*
❯ git shortlog --no-merges --summary --numbered --email --since 2014-10-18T19:57:04.307Z   
   264  Maxime Thirouin <...>
    57  Maxime Laforet <...>
     8  Erwann Mest <...>
     8  Baptiste Meurant <...>
     7  magsout <...>
     7  Uhsac <...>
     7  Guillaume Demesy <...>
     6  Sébastien Balayn <...>
     ...
```

**Comment by MoOx** [comment]
Maybe we should add activity from issues, but I am not sure we will get a huge differences.

**Comment by Nyalab** [comment]
why the hell not

**Comment by magsout** [comment]
I like this idea. The most active people would be owner ofp! ? What is the aim of an owner, or rather the power?

**Comment by MoOx** [comment]
> The most active people would be owner of p! ?

Why not? That make sense to me.

> What is the aim of an owner, or rather the power?

Just take decisions for "big" changes in the org/website (that said, everyone should give their opinion, that why I proposed https://github.com/putaindecode/organisation/issues/48). It's that simple. Not big deal imo.

**Comment by magsout** [comment]
>Why not? That make sense to me.

sounds good. like this idea. :+1: 

t's a great idea. I like the fact that the owner of the group are the most active users.

**Comment by MoOx** [comment]
You should see this at the opposite: most active users are the "owners" :)

**Comment by magsout** [comment]
Yeaaah ;) Is the Cup Half Full or Half Empty?

**Comment by MoOx** [comment]
haha

**Comment by lionelB** [comment]
go for it !
