### ISSUE TITLE
.fr -> .io

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#487]
- [x] use statinamic instead of metalsmith
- [x] merge translation PR posts
- [ ] change posts tree
- [ ] remove all references to putaindecode.fr (look for `](http://putaindecode.fr/`)
- [ ] update previous posts link in posts themselves (look for `](/posts/`)
- [ ] remove all useless `route:` metadata
- [ ] migrate disqus comments (export, update urls according to new tree, import)
- [ ] base homepage with distinction between fr/en/whatever
- [ ] fix "Articles" and similar links
- [ ] update travis and appveyor when repo is changed
- [ ] drop https://github.com/putaindecode/putaindecode.github.io repo
- [ ] update CNAME to putaindecode.io
- [ ] .fr on an Apache instance to rewrite .fr/* -> .io/fr/* with some cleanups (https://github.com/putaindecode/organisation/issues/35#issuecomment-112584566) according to new (posts) tree
- [ ] check DNS
- [ ] rename http://putaindecode.io/tab/ to http://tab.putaindecode.io/ (CNAME + redirection in putaindecode.io repo)

**Comment by MoOx** [comment]
Any idea for the homepage / ?
/{lang}/ will be current homepage translated, but not sure what to place on /

**Comment by magsout** [comment]
IMO

putaindecode.io/{lang}/
putaindecode.io/{lang}/posts/

etc...

**Comment by MoOx** [comment]
Yes but what should we place on / ?

**Comment by magsout** [comment]
Just c/p your proposal on discord
an home page with english et french choice

**Comment by MoOx** [comment]
Question related to putaindecode.io/tab we will need to rename this repo to putaindecode.github.io in order to keep putaindecode/{projects}#gh-pages to work as folder under the defined CNAME. Does that sounds weird to you guys?

**Comment by MoOx** [comment]
(I found this weird, but I am not sure we have other easy solutions)

**Comment by Macxim** [comment]
That's the logical thing to do. I don't find it weird.

**Comment by MoOx** [comment]
so
putaindecode.fr repo => putaindecode.io (no putaindecode.github.io)
putaindecode.io/tab url => tab.putaindecode.io (the only user (@macxim) seems ok with that)

**Comment by MoOx** [comment]
Closing in favor of https://github.com/putaindecode/putaindecode.fr/pull/524
