### ISSUE TITLE
Switch from Slack to Discord

### ISSUE THREAD

**Issue by MoOx** [putaindecode/putaindecode.fr#493]
Even if there is no IRC bridge yet (reactiflux community is working on it), we already have 43 members in the Discord server.
On Slack we have 113 members BUT 77 inactives, so only 36 active members.

Also, Discord invite links allow to point to a channel, so for the en/fr issue, it's already solved, "en" from incoming .io/en, "fr", for .io/fr.

:+1: / :-1: ?

**Comment by kud** [comment]
:-1:

**Comment by madx** [comment]
Define "active"

How much active users on Discord ?

**Comment by kud** [comment]
I stopped to read at:

> Even if there is no IRC bridge yet

**Comment by MoOx** [comment]
@madx 

- inactive: no connection to the service for some weeks, from what I know.
- discord, no idea, but since we are trying it for a week...

**Comment by MoOx** [comment]
The WIP bridge https://github.com/reactiflux/discord-irc
If someone want to try to setup it, be my guest.

**Comment by madx** [comment]
I took a look at this repo and it's not the bridge we are expecting, and it does not seem really built for being used by multiple users at once

I'll take some more time to see what we can do about it

**Comment by magsout** [comment]
:+1:

**Comment by Nyalab** [comment]
of course, yes. Reactiflux with its rock star devs has done it, we can do it

**Comment by MoOx** [comment]
FYI

![screen shot 2015-10-27 at 13 42 52](https://cloud.githubusercontent.com/assets/157534/10758265/b20c4e5c-7cb0-11e5-8557-826468ac859f.png)

**Comment by MoOx** [comment]
poke @Macxim @bloodyowl @lionelB

**Comment by lionelB** [comment]
Moi je suis pour. 
(En fait, j'ai déjà migré)

**Comment by Macxim** [comment]
Oui, mais ce serait dommage de perdre les gens qui sont sur IRC. Donc j'espère que le bridge sera opérationnel bientôt.

**Comment by MoOx** [comment]
Bridge is working, it just require some setup. I guess interested people should take care of it.
I don't think we have a lot of irc users
Even @madx use Discord (web?) while the bridge is ok for your discord server.

I will change Slack to Discord in #487 since most of you guys are ok.

**Comment by MoOx** [comment]
What about this icon http://iconmonstr.com/speech-bubble-15-icon/ + label: "Discuter" ?

**Comment by MoOx** [comment]
up for the icon guys

**Comment by MoOx** [comment]
Preview ![screen shot 2015-11-04 at 09 12 54](https://cloud.githubusercontent.com/assets/157534/10932822/43843b1e-82d4-11e5-8870-bf19a1aff4a1.png)

I like the fact that this icon differentiate from the 2 others. It emphasize the link.

**Comment by magsout** [comment]
Looks good to me :+1: 

Yes, no more update if in the future we add another service ;)
