### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by bloodyowl** [putaindecode/putaindecode.fr#503]
- [ ] pages should have a loader or optimistic rendering instead of nothing when loading content
- [ ] String.prototype.repeat is in core-js
- [ ] icons should preferably be inlined
- [ ] declare stateless components as plain functions
- [ ] PropTypes.array.isRequired for `this.props.children` is incorrect (opaque type)
- [ ] CSS modules should be used instead of concat

**Comment by MoOx** [comment]
1: #500 
2: polyfill folder is not used, can be dropped I think
3: icons are inlined via raw-loader, having an .svg can be nice for maintenance
4: sure
5: what is the best way to validate children ?
6: sure, but here that's a big deal

I think we should open issue for each bullets we are agree on.

**Comment by MoOx** [comment]
Closing in favor of #500 #506 #508 #509 #510 
Not sure for svg inlined in components yet (anyway, not a big deal we don't have too many).
