### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by leoderbois** [putaindecode/putaindecode.fr#514]
la page http://putaindecode.fr/putaindecode/putaindecode.fr/graphs/contributors renvoi un 404, rien de plus à dire :)

**Comment by MoOx** [comment]
Lol it seems we are using a Link component in place of a simple anchor poke @magsout

**Comment by magsout** [comment]
Yes, I will take a look

**Comment by MoOx** [comment]
Maybe we should even report this to react-router since the generated dom seems ok (href seems good on the website, that's the weird part)
