### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by feelpix** [putaindecode/putaindecode.fr#518]
Bonjour, 

Page not found : http://putaindecode.fr/feed.xml 

Or j'aimerai bien ajouter votre site dans mes flux RSS.

Merci.

**Comment by MoOx** [comment]
This url work has expected, so you can safely use it. However, the navigation system on our front-end is not handling it correctly and creating a fake 404 error.
Thanks for reporting, I will fix that asap.
